language: java
services:
  - mongodb
script: mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true
after_success:
  - mvn coveralls:report

notifications:
    slack: cylab-be:VmUKJZod81wbNyfme4nyrYo8
